function buildVisualTraits({
  melanin,
  eyeColor,
  hairPattern,
  noseShape,
  lipFullness,
  facialStructure,
  jawLine,
  cheekboneStructure,
  tribe,
}) {
  return [
    { id: 'melanin', label: 'Melanin Index', value: melanin, category: 'physical' },
    { id: 'eye-color', label: 'Eye Color', value: eyeColor, category: 'physical' },
    { id: 'hair', label: 'Hair Pattern', value: hairPattern, category: 'physical' },
    { id: 'nose', label: 'Nose Shape', value: noseShape, category: 'physical' },
    { id: 'lips', label: 'Lip Fullness', value: lipFullness, category: 'physical' },
    { id: 'facial', label: 'Facial Structure', value: facialStructure, category: 'physical' },
    { id: 'jaw', label: 'Jaw Line', value: jawLine, category: 'physical' },
    { id: 'cheekbone', label: 'Cheekbone Structure', value: cheekboneStructure, category: 'physical' },
    { id: 'tribe', label: 'Tribe', value: tribe, category: 'tribal' },
  ]
}

export const userPhenotype = {
  id: 'nordic-atlantic-7',
  name: 'Nordic-Atlantic VII',
  code: 'GN-NA7',
  tagline: 'North Sea lineage, strong tribal markers',
  traits: buildVisualTraits({
    melanin: 72,
    eyeColor: 67,
    hairPattern: 55,
    noseShape: 48,
    lipFullness: 52,
    facialStructure: 61,
    jawLine: 58,
    cheekboneStructure: 64,
    tribe: 84,
  }),
  genealogyLikelihood: 78,
  genealogyLineage: 'Nordic-Atlantic, generation depth 4',
}

export const matches = [
  {
    phenotype: {
      id: 'mediterranean-3',
      name: 'Mediterranean Basin III',
      code: 'GN-MB3',
      tagline: 'Southern coastal lineage, olive melanin range',
      traits: buildVisualTraits({
        melanin: 45,
        eyeColor: 52,
        hairPattern: 68,
        noseShape: 71,
        lipFullness: 63,
        facialStructure: 74,
        jawLine: 66,
        cheekboneStructure: 59,
        tribe: 79,
      }),
      genealogyLikelihood: 91,
      genealogyLineage: 'Mediterranean basin, generation depth 6',
    },
    sharedTraits: ['Overlapping tribal markers', 'Complementary melanin range'],
    complementaryTraits: ['Adjacent genealogy clusters with compatible depth'],
    distance: '2.3 mi',
    age: 27,
    virginity: 'non-virgin',
    genealogy: 91,
  },
  {
    phenotype: {
      id: 'north-sea-12',
      name: 'North Sea Coastal XII',
      code: 'GN-NS12',
      tagline: 'Coastal Nordic lineage, high tribal confidence',
      traits: buildVisualTraits({
        melanin: 68,
        eyeColor: 74,
        hairPattern: 82,
        noseShape: 44,
        lipFullness: 49,
        facialStructure: 58,
        jawLine: 62,
        cheekboneStructure: 71,
        tribe: 91,
      }),
      genealogyLikelihood: 85,
      genealogyLineage: 'North Sea coastal, generation depth 5',
    },
    sharedTraits: ['Matched eye color range', 'Same genealogy cluster'],
    complementaryTraits: ['Higher tribal confidence reinforces your lineage estimate'],
    distance: '4.1 mi',
    age: 24,
    virginity: 'virgin',
    genealogy: 85,
  },
  {
    phenotype: {
      id: 'central-euro-5',
      name: 'Central European V',
      code: 'GN-CE5',
      tagline: 'Mixed continental lineage, moderate tribal signal',
      traits: buildVisualTraits({
        melanin: 81,
        eyeColor: 59,
        hairPattern: 47,
        noseShape: 55,
        lipFullness: 57,
        facialStructure: 66,
        jawLine: 53,
        cheekboneStructure: 48,
        tribe: 62,
      }),
      genealogyLikelihood: 72,
      genealogyLineage: 'Central European mixed, generation depth 3',
    },
    sharedTraits: ['Close melanin index', 'Similar facial structure'],
    complementaryTraits: ['Bridging genealogy between Atlantic and continental lines'],
    distance: '6.8 mi',
    age: 31,
    virginity: 'undisclosed',
    genealogy: 72,
  },
  {
    phenotype: {
      id: 'baltic-9',
      name: 'Baltic Fringe IX',
      code: 'GN-BF9',
      tagline: 'Eastern fringe lineage, distinct eye color lattice',
      traits: buildVisualTraits({
        melanin: 33,
        eyeColor: 93,
        hairPattern: 56,
        noseShape: 62,
        lipFullness: 41,
        facialStructure: 71,
        jawLine: 77,
        cheekboneStructure: 83,
        tribe: 88,
      }),
      genealogyLikelihood: 63,
      genealogyLineage: 'Baltic fringe, generation depth 7',
    },
    sharedTraits: ['Strong tribal overlap', 'Rare eye color lattice match'],
    complementaryTraits: ['Deeper generation depth extends your lineage tree'],
    distance: '8.2 mi',
    age: 29,
    virginity: 'non-virgin',
    genealogy: 63,
  },
]

export const filterOptions = {
  virginity: ['any', 'virgin', 'non-virgin', 'undisclosed'],
  genealogy: [
    { label: 'Any', min: 0 },
    { label: '60%+', min: 60 },
    { label: '70%+', min: 70 },
    { label: '80%+', min: 80 },
    { label: '90%+', min: 90 },
  ],
  age: [
    { label: '18–24', min: 18, max: 24 },
    { label: '25–30', min: 25, max: 30 },
    { label: '31–40', min: 31, max: 40 },
    { label: 'Any age', min: 18, max: 99 },
  ],
}

export const scanSteps = [
  'Loading cloud optical pipeline…',
  'Analyzing melanin distribution…',
  'Reading eye color…',
  'Assessing hair pattern…',
  'Mapping nose shape…',
  'Measuring lip fullness…',
  'Mapping facial structure…',
  'Reading jaw line…',
  'Assessing cheekbone structure…',
  'Inferring tribal markers…',
  'Computing genealogy likelihood…',
  'Building pheno profile…',
]
